### PR TITLE
Fix #3 - Adding 2 buttons Clear and Retrieve

### LINKED ISSUE #3: Adding "Clear" button
I think it would be nice to add "Clear" button on the page to clear the contents of the note. Please let me know if I can work on it. Thank you

### PR DESCRIPTION
**Pull request by lozinska**
Button Clear will clear the contents of the notepad. Button Retrieve Previous Info will retrieve data that had been cleared

### CODE REVIEW

**Comment by smilegodly** [comment]
Hi, 
When I was testing this feature, "Retrieve Previous Info" was not restoring what I previously had cleared, and I lost all my data after clearing it .. 

Also using center alignment on  the buttons would look a bit nicer I think.

To replicate this issue ..
```
Type some input...
hit "Clear"
Wait 3-5 seconds
hit "Retrieve previous info"
The previous information does not get restored...
```



Thanks,

**Comment by lozinska** [comment]
Hi. Thank you for letting me know. Sure I will work on fixing this bug

**Review by smilegodly — DISMISSED** [review]
When I was testing this feature, "Retrieve Previous Info" was not restoring what I previously had cleared.
To replicate the issue.
```
Type some input...
hit "Clear"
Wait 3-5 seconds
hit "Retrieve previous info"
The previous information does not get restored...
```
This bug is caused by the code on line 62:
```js
setInterval(save, 3000);
```
If the code writes/saves once the user has hit the clear button, the previous content is unrestorable.
One way this bug can be fixed is by making the save interval longer , maybe 15-20 seconds and having the user know when the contents are being saved.

**Comment by lozinska** [comment]
That what i was thinking about as well. Thank you for helping me, I will do the way you said

**Comment by lozinska** [comment]
I just updated pull request. When you will have opportunity can you check please. Thank you

**Comment by smilegodly** [comment]
There are a few issues here...

Your branch is 4 commits behind my master it says, so you need to update your branch I think.
 
Second, The alert saying its 'Data is saved' messes with typing on the app, which I don't want on the app
Also the buttons aren't aligned nicely on the page .
image

I like this feature, and will merge with master whenever these changes happen.

**Comment by lozinska** [comment]
Hi Matthew I have updated my files according with your master branch, move buttons and add message that let user know about auto savings. Please let me know if that is what you expect to see in your app. Thank you

**Review by smilegodly — COMMENTED** [review]
Your code was not aligning the buttons properly,

image

I have committed a change to your repository which fixes this alignment issue.

**Comment by lozinska** [comment]
Ok thank you.

**Pull request merged**
